In [48]:
!rm -rf ~/.cache/pip

In [5]:
from transformers import AutoTokenizer, AutoModel, BertModel, BertTokenizer

In [39]:
!cd data; wget http://files.deeppavlov.ai/deeppavlov_data/bert/sentence_ru_cased_L-12_H-768_A-12_pt.tar.gz

--2021-01-25 18:53:32--  http://files.deeppavlov.ai/deeppavlov_data/bert/sentence_ru_cased_L-12_H-768_A-12_pt.tar.gz
Resolving files.deeppavlov.ai (files.deeppavlov.ai)... 93.175.29.74
Connecting to files.deeppavlov.ai (files.deeppavlov.ai)|93.175.29.74|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 661614603 (631M) [application/octet-stream]
Saving to: ‘sentence_ru_cased_L-12_H-768_A-12_pt.tar.gz’

sentence_ru_cased_L 100%[===================>] 630.96M  4.93MB/s    in 1m 44s  

2021-01-25 18:55:17 (6.05 MB/s) - ‘sentence_ru_cased_L-12_H-768_A-12_pt.tar.gz’ saved [661614603/661614603]



In [40]:
!cd data; tar -xf sentence_ru_cased_L-12_H-768_A-12_pt.tar.gz

In [3]:
model = BertModel.from_pretrained('data/sentence_ru_cased_L-12_H-768_A-12_pt/')

In [6]:
tokenizer = BertTokenizer.from_pretrained('data/sentence_ru_cased_L-12_H-768_A-12_pt')

In [19]:
inputs = tokenizer("Bye!", return_tensors="pt")
outputs = model(**inputs)

In [30]:
outputs

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 0.0894, -0.1153, -0.9755,  ...,  0.3169, -0.1946,  0.3348],
         [ 0.1384, -0.1286, -0.9826,  ...,  0.3455, -0.0663,  0.3860],
         [ 0.1549, -0.0929, -0.7338,  ...,  0.3314, -0.0300,  0.3673],
         [ 0.0808, -0.0677, -0.9090,  ...,  0.2362, -0.2428,  0.3858],
         [ 0.0328, -0.1471, -0.8681,  ...,  0.0561, -0.2288,  0.4276]]],
       grad_fn=<NativeLayerNormBackward>), pooler_output=tensor([[-1.9437e-01, -5.2679e-01,  3.2183e-01,  1.0898e-05, -1.6951e-01,
          2.1788e-01,  4.0349e-01, -1.9077e-02,  2.1392e-01,  1.4755e-01,
         -5.7718e-01,  2.7898e-01,  1.9065e-02,  2.4579e-01,  9.8032e-02,
         -4.4434e-02, -2.8958e-01,  1.9416e-01,  2.2305e-01, -1.5817e-01,
          7.3847e-02, -1.2277e-01, -2.7264e-02, -2.0631e-02,  4.4292e-01,
          2.7201e-02, -3.6224e-01,  3.8718e-01, -6.8878e-02, -2.3254e-01,
         -6.8433e-02,  2.8932e-01,  5.2349e-01,  8.9582e-03,  2.7160e-01,
     

In [14]:
hw = outputs[1].detach().numpy()

In [16]:
pric = outputs[1].detach().numpy()

In [18]:
bye = outputs[1].detach().numpy()

In [20]:
bye_end = outputs[1].detach().numpy()

In [25]:
import numpy as np
np.inner(hw, pric), np.inner(hw, bye), np.inner(hw, bye_end), np.inner(pric, bye)

(array([[62.40195]], dtype=float32),
 array([[57.47644]], dtype=float32),
 array([[53.481606]], dtype=float32),
 array([[71.1021]], dtype=float32))